###
POST http://127.0.0.1:8000/data/explorer/similarity/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="digits_crop_test_img.jpg"

< ../resources/digits_crop_test_img.jpg

--WebAppBoundary
Content-Disposition: form-data; name="dataset_file"; filename="test_yolo_dataset.zip"

< ../resources/test_yolo_dataset.zip

--WebAppBoundary--
Content-Disposition: form-data; name="split_parameter"

train
--WebAppBoundary--

###
POST http://127.0.0.1:8000/data/explorer/query/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="dataset_file"; filename="test_yolo_dataset.zip"

< ../resources/test_yolo_dataset.zip

--WebAppBoundary
Content-Disposition: form-data; name="query_parameter"

SELECT * FROM 'table' WHERE labels LIKE '%0%' AND labels LIKE '%1%'
--WebAppBoundary--
Content-Disposition: form-data; name="split_parameter"

train
--WebAppBoundary--

###