###
POST http://127.0.0.1:8000/sahi/yolo_v8/digits/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="digits_test_img.jpg"

< ../resources/digits_test_img.jpg

--WebAppBoundary
Content-Disposition: form-data; name="slice_size_width_parameter"

160
--WebAppBoundary--
Content-Disposition: form-data; name="slice_size_height_parameter"

160
--WebAppBoundary--
Content-Disposition: form-data; name="slice_overlap_ratio_width_parameter"

0.3
--WebAppBoundary--
Content-Disposition: form-data; name="slice_overlap_ratio_height_parameter"

0.3
--WebAppBoundary--

###
POST http://127.0.0.1:8000/sahi/yolo_v8/glyphs/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="glyphs_test_img.jpg"

< ../resources/glyphs_test_img.jpg

--WebAppBoundary
Content-Disposition: form-data; name="slice_size_width_parameter"

160
--WebAppBoundary--
Content-Disposition: form-data; name="slice_size_height_parameter"

160
--WebAppBoundary--
Content-Disposition: form-data; name="slice_overlap_ratio_width_parameter"

0.3
--WebAppBoundary--
Content-Disposition: form-data; name="slice_overlap_ratio_height_parameter"

0.3
--WebAppBoundary--

###