###
POST http://127.0.0.1:8000/yolo_v8/digits/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="digits_crop_test_img.jpg"

< ../resources/digits_crop_test_img.jpg

--WebAppBoundary
Content-Disposition: form-data; name="confidence_parameter"

0.5
--WebAppBoundary--
Content-Disposition: form-data; name="iou_parameter"

0.7
--WebAppBoundary--
Content-Disposition: form-data; name="image_size_parameter"

640
--WebAppBoundary--

###
POST http://127.0.0.1:8000/yolo_v8/glyphs/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="glyphs_crop_test_img.jpg"

< ../resources/glyphs_crop_test_img.jpg

--WebAppBoundary

###
POST http://127.0.0.1:8000/yolo_v9/digits/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="digits_crop_test_img.jpg"

< ../resources/digits_crop_test_img.jpg

--WebAppBoundary

###
POST http://127.0.0.1:8000/yolo_v9/glyphs/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="glyphs_crop_test_img.jpg"

< ../resources/glyphs_crop_test_img.jpg

--WebAppBoundary

###
POST http://127.0.0.1:8000/yolo_world_v2/digits/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="digits_crop_test_img.jpg"

< ../resources/digits_crop_test_img.jpg

--WebAppBoundary

###
POST http://127.0.0.1:8000/yolo_world_v2/glyphs/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="glyphs_crop_test_img.jpg"

< ../resources/glyphs_crop_test_img.jpg

--WebAppBoundary

###
POST http://127.0.0.1:8000/rt_detr/digits/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="digits_crop_test_img.jpg"

< ../resources/digits_crop_test_img.jpg

--WebAppBoundary

###
POST http://127.0.0.1:8000/rt_detr/glyphs/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="glyphs_crop_test_img.jpg"

< ../resources/glyphs_crop_test_img.jpg

--WebAppBoundary

###
POST http://127.0.0.1:8000/fast_sam/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image_file"; filename="digits_crop_test_img.jpg"

< ../resources/digits_crop_test_img.jpg

--WebAppBoundary

###